"""Regenerate the Uiyeun webfont assets.

Run:  python scripts/build-font.py

Why this exists
---------------
Mobile browsers (Samsung Internet, mobile Safari) kept dropping the
webfont and falling back to the system font, while desktop browsers and
in-app webviews loaded it fine. Every delivery tweak we tried still
boiled down to "the browser must fetch a font file", so anything that
blocks font *requests* -- content blockers, data-saver modes -- broke it.

So the text that is actually on screen no longer involves a request at
all: it is subset down to just the characters the app itself renders and
embedded straight into CSS as a data: URI. There is no URL to block.

Everything else (student names, which are dynamic) rides in a second,
normally-fetched file. If that one is ever blocked, only names degrade
to the system font -- the interface itself still looks right.

Outputs
-------
  app/font.css                     @font-face rules; layer 1 inlined
  public/fonts/uiyeun-names.woff2  layer 2, fetched on demand
"""

import base64
import glob
import os
import re

from fontTools.subset import Options, Subsetter
from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "Uiyeun-Regular.woff2")
APP = os.path.join(ROOT, "app")
CSS_OUT = os.path.join(APP, "font.css")
NAMES_OUT = os.path.join(ROOT, "public", "fonts", "uiyeun-names.woff2")

LATIN = list(range(0x0020, 0x007F))
PUNCT = [0x00A0, 0x00B7, 0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2026, 0x2726]


def ui_codepoints():
    """Every Hangul syllable the app's own source renders, plus ASCII."""
    chars = set()
    for pattern in ("**/*.tsx", "**/*.ts"):
        for path in glob.glob(os.path.join(APP, pattern), recursive=True):
            chars |= set(open(path, encoding="utf-8").read())
    hangul = {ord(c) for c in chars if 0xAC00 <= ord(c) <= 0xD7A3}
    return sorted(hangul | set(LATIN) | set(PUNCT))


def ksx1001():
    """The 2,350 KS X 1001 syllables -- covers essentially every Korean name.

    Python's euc_kr codec is really CP949, which encodes all 11,172
    syllables, so filter on the lead byte to get true KS X 1001.
    """
    out = []
    for cp in range(0xAC00, 0xD7A4):
        try:
            b = chr(cp).encode("euc_kr")
        except UnicodeEncodeError:
            continue
        if len(b) == 2 and 0xB0 <= b[0] <= 0xC8:
            out.append(cp)
    assert len(out) == 2350, f"expected 2350 KS X 1001 syllables, got {len(out)}"
    return out


def to_unicode_range(codepoints):
    """Collapse a codepoint list into a CSS unicode-range value."""
    parts = []
    start = prev = codepoints[0]
    for cp in codepoints[1:]:
        if cp == prev + 1:
            prev = cp
            continue
        parts.append((start, prev))
        start = prev = cp
    parts.append((start, prev))
    return ",".join(
        f"U+{a:04X}" if a == b else f"U+{a:04X}-{b:04X}" for a, b in parts
    )


def subset(codepoints, path):
    opts = Options()
    opts.glyph_names = False
    opts.hinting = False
    opts.desubroutinize = True
    opts.layout_features = []
    opts.notdef_outline = True
    opts.recalc_bounds = True
    opts.recalc_timestamp = False
    opts.drop_tables = ["FFTM"]
    opts.flavor = "woff2"

    font = TTFont(SRC)
    s = Subsetter(options=opts)
    s.populate(unicodes=codepoints)
    s.subset(font)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    font.save(path)
    return os.path.getsize(path)


def face(src, unicode_range):
    return (
        "@font-face{"
        "font-family:'Uiyeun';"
        "font-weight:400;"
        "font-style:normal;"
        "font-display:swap;"
        f"src:{src};"
        f"unicode-range:{unicode_range}"
        "}"
    )


def main():
    ui = ui_codepoints()
    names = sorted(set(ksx1001()) - set(ui))

    tmp = os.path.join(ROOT, ".uiyeun-ui.tmp.woff2")
    ui_size = subset(ui, tmp)
    ui_b64 = base64.b64encode(open(tmp, "rb").read()).decode("ascii")
    os.remove(tmp)

    names_size = subset(names, NAMES_OUT)

    css = "\n".join([
        "/* GENERATED by scripts/build-font.py -- do not edit by hand. */",
        "",
        "/* Layer 1: every character the interface itself renders, embedded",
        "   as a data: URI. No network request, so nothing can block it. */",
        face(
            f"url(data:font/woff2;base64,{ui_b64}) format('woff2')",
            to_unicode_range(ui),
        ),
        "",
        "/* Layer 2: the rest of KS X 1001, for student names. Fetched only",
        "   when such a character is on screen; if it is ever blocked, only",
        "   names fall back to the system font. */",
        face(
            "url('/fonts/uiyeun-names.woff2') format('woff2')",
            to_unicode_range(names),
        ),
        "",
    ])
    open(CSS_OUT, "w", encoding="utf-8", newline="\n").write(css)

    print(f"layer 1  {len(ui):5d} chars  {ui_size:>8,} B  -> inlined ({len(ui_b64)/1024:.0f} KB base64)")
    print(f"layer 2  {len(names):5d} chars  {names_size:>8,} B  -> {os.path.relpath(NAMES_OUT, ROOT)}")
    print(f"wrote    {os.path.relpath(CSS_OUT, ROOT)}  ({os.path.getsize(CSS_OUT)/1024:.0f} KB)")


if __name__ == "__main__":
    main()
